name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Bundle
        run: |
          npm install
          npm run build

      - name: Zip
        run: |
          cd dist
          zip -r ../ui.zip ./*

      - name: Test
        run: cat ui.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ui.zip