name: Release

on: push

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: |
          npm install
          npm run build

      - name: Zip
        run: |
          cd dist
          zip -r ../ui.zip ./*

      - name: Test
        run: cat ui.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ui.zip